# fly.toml app configuration file generated for staging-dt-12-8-1723465702-server on 2024-08-12T12:29:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'staging-dt-12-8-1723465702-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
